INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('1','Expense Manager','App','Lifestyle','Android',to_date('2014-01-01', 'yyyy-mm-dd'),0.00,0.00,0.0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('2','EverNote','App','Productivity','iOS',to_date('2013-04-03', 'yyyy-mm-dd'),0.99,0.00,0.0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('3','Scandal Season 1','TV','Thriller','None',to_date('2014-01-02', 'yyyy-mm-dd'),20.00,6.00,0.0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('4','Suits Season 1','TV','Drama','None',to_date('2014-01-03', 'yyyy-mm-dd'),20.00,9.00,0.0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('5','Brave Frontier','Game','RPG','Android',to_date('2013-02-23', 'yyyy-mm-dd'),0.00,0.00,0.0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('6','The Hobbit: An Unexpected Journey','Movie','Fantasy','DVD',to_date('2012-12-15', 'yyyy-mm-dd'),30.00,13.00,0.0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('7','Memorado','App','Lifestyle','iOS',to_date('2014-10-30', 'yyyy-mm-dd'),33,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('8','Learn Spanish, English, French','App','Productivity','Android',to_date('2014-11-23', 'yyyy-mm-dd'),18,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('9','DIY Human Body','App','Lifestyle','PC',to_date('2013-06-13', 'yyyy-mm-dd'),13,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('10','RefMe','App','Productivity','iOS',to_date('2015-02-17', 'yyyy-mm-dd'),56,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('11','Duolingo','App','Lifestyle','Android',to_date('2014-10-22', 'yyyy-mm-dd'),49,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('12','Peak - Brain Training','App','Productivity','PC',to_date('2014-05-13', 'yyyy-mm-dd'),52,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('13','IELTS 1001 ways','App','Lifestyle','iOS',to_date('2013-08-21', 'yyyy-mm-dd'),10,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('14','Explain Everything','App','Productivity','Android',to_date('2014-05-31', 'yyyy-mm-dd'),11,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('15','Lumosity Mobile','App','Lifestyle','PC',to_date('2014-05-08', 'yyyy-mm-dd'),37,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('16','PhotoMath','App','Productivity','iOS',to_date('2015-02-05', 'yyyy-mm-dd'),42,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('17','Molecules by Theodore Gray','App','Lifestyle','Android',to_date('2013-06-11', 'yyyy-mm-dd'),56,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('18','LearnEnglish Kids: Playtime','App','Productivity','PC',to_date('2014-01-10', 'yyyy-mm-dd'),18,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('19','Night Sky Pro','App','Lifestyle','iOS',to_date('2014-12-29', 'yyyy-mm-dd'),54,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('20','Collins English Dictionary','App','Productivity','Android',to_date('2013-01-27', 'yyyy-mm-dd'),11,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('21','Game of Thrones','TV','Thriller','None',to_date('2015-02-07', 'yyyy-mm-dd'),47,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('22','Arrow','TV','Drama','None',to_date('2014-03-19', 'yyyy-mm-dd'),19,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('23','Marvel''s Agents Of S.H.I.E.L.D','TV','Horror','None',to_date('2013-08-30', 'yyyy-mm-dd'),9,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('24','Grey''s Anatomy','TV','Science','None',to_date('2014-12-29', 'yyyy-mm-dd'),39,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('25','Coronation Street','TV','Thriller','None',to_date('2015-01-03', 'yyyy-mm-dd'),22,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('26','The Vampire Diaries','TV','Drama','None',to_date('2014-02-01', 'yyyy-mm-dd'),48,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('27','The Big Bang Theory','TV','Horror','None',to_date('2014-07-20', 'yyyy-mm-dd'),22,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('28','Supernatural','TV','Science','None',to_date('2014-12-26', 'yyyy-mm-dd'),2,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('29','How I Met Your Mother','TV','Thriller','None',to_date('2013-01-21', 'yyyy-mm-dd'),40,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('30','Once Upon a Time','TV','Drama','None',to_date('2013-06-14', 'yyyy-mm-dd'),45,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('31','Criminal Minds','TV','Horror','None',to_date('2013-06-24', 'yyyy-mm-dd'),13,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('32','The Blacklist','TV','Science','None',to_date('2015-02-10', 'yyyy-mm-dd'),52,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('33','The 100','TV','Thriller','None',to_date('2013-08-07', 'yyyy-mm-dd'),44,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('34','The Mentalist','TV','Drama','None',to_date('2013-12-24', 'yyyy-mm-dd'),32,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('35','The Good Wife','TV','Horror','None',to_date('2014-11-09', 'yyyy-mm-dd'),43,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('36','NCIS','TV','Science','None',to_date('2014-12-05', 'yyyy-mm-dd'),31,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('37','Vikings','TV','Thriller','None',to_date('2013-03-20', 'yyyy-mm-dd'),21,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('38','Castle','TV','Drama','None',to_date('2013-02-27', 'yyyy-mm-dd'),43,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('39','Revenge','TV','Horror','None',to_date('2013-02-23', 'yyyy-mm-dd'),25,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('40','Bones','TV','Science','None',to_date('2014-07-24', 'yyyy-mm-dd'),56,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('41','Final Fantasy XIII','Game','RPG','PC',to_date('2014-12-30', 'yyyy-mm-dd'),51,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('42','Final Fantasy XIII-2','Game','RPG','PC',to_date('2013-02-12', 'yyyy-mm-dd'),53,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('43','Final Fantasy: Lightning Returns','Game','RPG','PC',to_date('2013-01-09', 'yyyy-mm-dd'),58,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('44','Clash of Clans','Game','None','iOS',to_date('2013-08-10', 'yyyy-mm-dd'),22,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('45','Angry Birds','Game','None','Android',to_date('2014-05-08', 'yyyy-mm-dd'),30,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('46','Defense of the Ancients','Game','None','PC',to_date('2014-11-15', 'yyyy-mm-dd'),55,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('47','Card Craawl','Game','None','iOS',to_date('2014-11-15', 'yyyy-mm-dd'),57,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('48','Word Shark','Game','None','Android',to_date('2014-05-23', 'yyyy-mm-dd'),15,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('49','Shadow of Mordor','Game','None','PC',to_date('2013-09-27', 'yyyy-mm-dd'),39,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('50','Dotello','Game','None','iOS',to_date('2014-08-03', 'yyyy-mm-dd'),41,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('51','Hero Sky','Game','None','Android',to_date('2013-10-24', 'yyyy-mm-dd'),7,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('52','Green the Planet','Game','None','PC',to_date('2013-03-10', 'yyyy-mm-dd'),17,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('53','Paper Monsters Recut','Game','None','iOS',to_date('2014-03-02', 'yyyy-mm-dd'),34,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('54','rop','Game','None','Android',to_date('2013-02-16', 'yyyy-mm-dd'),22,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('55','Sick Bricks','Game','None','PC',to_date('2014-06-08', 'yyyy-mm-dd'),51,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('56','Contract Killer','Game','None','iOS',to_date('2014-04-24', 'yyyy-mm-dd'),6,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('57','Bejewel','Game','None','Android',to_date('2013-08-30', 'yyyy-mm-dd'),26,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('58','Call Of Duty: Mordern Warfare','Game','None','PC',to_date('2013-03-27', 'yyyy-mm-dd'),43,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('59','Valkyrie Crusade','Game','None','iOS',to_date('2013-03-19', 'yyyy-mm-dd'),32,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('60','Amazons Board Games','Game','None','Android',to_date('2013-07-31', 'yyyy-mm-dd'),26,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('61','Cinderella','Movie','Thriller','DVD',to_date('2013-09-17', 'yyyy-mm-dd'),32,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('62','The Spongebob Movie','Movie','Horror','DVD',to_date('2014-10-30', 'yyyy-mm-dd'),59,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('63','Interstellar','Movie','Popular','DVD',to_date('2013-11-29', 'yyyy-mm-dd'),38,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('64','Insurgent','Movie','Romance','DVD',to_date('2014-07-31', 'yyyy-mm-dd'),2,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('65','Divergent','Movie','Thriller','DVD',to_date('2014-11-29', 'yyyy-mm-dd'),42,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('66','ZhongKui','Movie','Horror','DVD',to_date('2014-12-12', 'yyyy-mm-dd'),37,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('67','Unfinished Business','Movie','Popular','DVD',to_date('2014-05-12', 'yyyy-mm-dd'),1,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('68','Fashion King','Movie','Romance','DVD',to_date('2013-04-30', 'yyyy-mm-dd'),15,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('69','Barbie in Princess Power','Movie','Thriller','DVD',to_date('2013-05-17', 'yyyy-mm-dd'),53,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('70','Kingsman: The Secret Service','Movie','Horror','DVD',to_date('2013-11-13', 'yyyy-mm-dd'),11,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('71','Fifty Shades of Grey','Movie','Popular','DVD',to_date('2013-03-30', 'yyyy-mm-dd'),57,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('72','Frozen','Movie','Romance','DVD',to_date('2014-09-20', 'yyyy-mm-dd'),59,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('73','Asterix','Movie','Thriller','DVD',to_date('2014-01-11', 'yyyy-mm-dd'),59,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('74','Chappie','Movie','Horror','DVD',to_date('2013-05-25', 'yyyy-mm-dd'),39,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('75','Run All Night','Movie','Popular','DVD',to_date('2013-08-20', 'yyyy-mm-dd'),60,2,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('76','Truimph In the Skies','Movie','Romance','DVD',to_date('2015-01-27', 'yyyy-mm-dd'),12,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('77','King of Mahjong','Movie','Thriller','DVD',to_date('2013-10-29', 'yyyy-mm-dd'),4,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('78','Fireman','Movie','Horror','DVD',to_date('2014-01-07', 'yyyy-mm-dd'),38,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('79','Shaun The Sheep','Movie','Popular','DVD',to_date('2013-12-31', 'yyyy-mm-dd'),46,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('80','From Vegas To Macau','Movie','Romance','DVD',to_date('2013-07-02', 'yyyy-mm-dd'),22,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('81','Microsoft oneNote for iPhone','App','Lifestyle','iOS',to_date('2013-09-08', 'yyyy-mm-dd'),30,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('82','EverNote','App','Productivity','Android',to_date('2013-07-14', 'yyyy-mm-dd'),52,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('83','Post It Plus','App','Lifestyle','PC',to_date('2013-10-14', 'yyyy-mm-dd'),12,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('84','Bosimize','App','Productivity','iOS',to_date('2014-03-26', 'yyyy-mm-dd'),4,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('85','Ginger KeyBoard: Better Themes','App','Lifestyle','Andriod',to_date('2014-09-15', 'yyyy-mm-dd'),19,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('86','Notepad+','App','Productivity','PC',to_date('2014-02-05', 'yyyy-mm-dd'),28,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('87','ByWord','App','Lifestyle','iOS',to_date('2015-02-19', 'yyyy-mm-dd'),57,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('88','Daedalus Touch','App','Productivity','Android',to_date('2013-05-23', 'yyyy-mm-dd'),21,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('89','Notability','App','Lifestyle','PC',to_date('2013-10-19', 'yyyy-mm-dd'),36,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('90','GoodNotes','App','Productivity','iOS',to_date('2013-06-29', 'yyyy-mm-dd'),9,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('91','FetchNotes','App','Lifestyle','Android',to_date('2014-12-12', 'yyyy-mm-dd'),57,1,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('92','1Writer','App','Productivity','PC',to_date('2013-06-25', 'yyyy-mm-dd'),23,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('93','SwiftKey','App','Lifestyle','iOS',to_date('2014-09-10', 'yyyy-mm-dd'),7,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('94','WordBoard','App','Productivity','Android',to_date('2013-12-25', 'yyyy-mm-dd'),14,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('95','Christmas Keyboard','App','Lifestyle','iOS',to_date('2013-11-05', 'yyyy-mm-dd'),13,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('96','InkBoard','App','Productivity','Android',to_date('2014-12-23', 'yyyy-mm-dd'),1,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('97','TextExpander','App','Lifestyle','PC',to_date('2014-03-30', 'yyyy-mm-dd'),2,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('98','Phraseboard','App','Productivity','iOS',to_date('2014-11-21', 'yyyy-mm-dd'),28,4,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('99','Swype','App','Lifestyle','Android',to_date('2014-03-09', 'yyyy-mm-dd'),50,3,0);
INSERT INTO Item (item_id,title,category,genre,device,release_date,price,rent_price,rating) VALUES ('100','MyScriptStack','App','Productivity','PC',to_date('2014-06-05', 'yyyy-mm-dd'),38,3,0);
